### ISSUE TITLE
Cannot save splits / run on Java versions newer than Java 11

### ISSUE THREAD

**Issue by jpretori** [tgpethan/Llanfair#2]
I use Arch Linux.  I ran the latest release using this commandline: `$ java -jar Llanfair-r20211211-holly.jar`

All seems to work, until I try to save the run (right-click -> save as -> Enter filename -> click Save).  This produces no confirmation or error message on the UI, but it spits out this stack trace on the terminal.  No file is created.

```
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:679)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:456)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:381)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:356)
	at org.fenix.llanfair.Actions.save(Actions.java:419)
	at org.fenix.llanfair.Actions.process(Actions.java:138)
	at org.fenix.llanfair.Llanfair$3.run(Llanfair.java:515)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @4a499116
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:59)
	... 20 more

```

**Comment by jpretori** [comment]
Looks like it spat out some more stack trace when I exited the application:

```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:679)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:456)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:381)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:356)
	at org.fenix.utils.config.Configuration.serialize(Configuration.java:168)
	at org.fenix.llanfair.config.Settings.save(Settings.java:188)
	at org.fenix.llanfair.Llanfair$AppShutdown.run(Llanfair.java:59)
	at org.fenix.llanfair.Llanfair.windowClosed(Llanfair.java:478)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosed(AWTEventMulticaster.java:367)
	at java.desktop/java.awt.Window.processWindowEvent(Window.java:2088)
	at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
	at java.desktop/java.awt.Window.processEvent(Window.java:2044)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @4a499116 [in thread "AWT-EventQueue-0"]
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:59)
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:679)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:456)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:381)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:356)
	at org.fenix.llanfair.Actions.save(Actions.java:419)
	at org.fenix.llanfair.Actions.process(Actions.java:138)
	at org.fenix.llanfair.Llanfair$3.run(Llanfair.java:515)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	... 6 more
```

**Comment by tgpholly** [comment]
This looks like an issue when you run it with a Java version that is too new. It's compiled against Java 11 so try running it with that, I would bump it to a newer Java version but there are issues with doing that.
Sorry for only getting to this almost a year later.

**Comment by tgpholly** [comment]
Reproduced on Java 21, keeping this open as a reminder to try and get this up to a newer Java version.

**Comment by jpretori** [comment]
More FYI: 
I tried it with jre11-openjdk and had UI problems, and lots of nullpointer exceptions on the terminal.

So I tried with jre8-openjdk, and that seems to work fine at first glance.  Very few errors, UI is responsive and seems to work right.

**Comment by tgpholly** [comment]
That's not too surprising, this was originally designed to work on Java 7 and Java 8 isn't too dissimilar to it. Java 9 was where fairly major changes started happening to Java.
The NPE's are probably being caused by input hooking. That stuff has always had problems, even on Java 7 but bumping the version just causes even more issues.
I also run Arch (but run Wayland) so hopefully I can reproduce your issues, I'm a bit clogged up with work at the moment but I should be able to take a look some time this week.
I would like to get this off Java 11 to something newer (Like Java 21) ideally, I don't want to drop back to Java 8 as it is ***very*** old by this point.
